alert("teste de exercício 3")
const media1 = Number(prompt("Digite o peso da pessoa 1:"))
const media2 = Number(prompt("Digite o peso da pessoa 2:"))
const media3 = Number(prompt("Digite o peso da pessoa 3:"))
const media4 = Number(prompt("Digite o peso da pessoa 4:"))
const media5 = Number(prompt("Digite o peso da pessoa 5:"))
const media = ((media1+media2+media3+media4+media5)/5)
alert("A média dos pesos informados é:"+media)